# Use postgres/example user/password credentials
version: '3.1'

services:

  dbsql:
    image: postgres
    restart: always
    mem_limit: 512m
    cpus: 0.25
    environment:
      POSTGRES_PASSWORD: 1232451fafr8
      POSTGRES_USER: MsManager
      POSTGRES_DB: CalendarManager
    ports:
      - 5432:5432
  
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    mem_limit: 512m
    cpus: 0.25
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: gwohnfgj45*5
      RABBITMQ_DEFAULT_VHOST: dev
    ports:
      - 5672:5672
  
  nosqlmongo:
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: fhasgkr867fa654
    ports:
      - 27017:27017