# Use postgres/example user/password credentials
version: '3.1'

services:

  dbpostgres:
    image: postgres
    restart: always
    mem_limit: 512m
    cpus: 0.25
    environment:
      POSTGRES_PASSWORD: 1232451fafr8
      POSTGRES_USER: MsManager
      POSTGRES_DB: CalendarManager
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4:6.14
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: luismigueldiazmorales@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1232451fafr8
    ports:
      - 8083:80
    volumes:
      - ./volumes/pgadmin-data:/var/lib/pgadmin
    depends_on: 
      - dbpostgres
  
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    mem_limit: 512m
    cpus: 0.25
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: gwohnfgj45*5
      RABBITMQ_DEFAULT_VHOST: dev
    ports:
      - 5672:5672
      - 8082:15672
  
  nosqlmongo:
    image: mongo:5.0
    restart: always
    mem_limit: 512m
    cpus: 0.25
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: fhasgkr867fa654
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongodb:/data/db
  
  mongoexpress:
    image: mongo-express:0.54.0
    restart: always
    mem_limit: 512m
    cpus: 0.25
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: luismigueldiazmorales
      ME_CONFIG_BASICAUTH_PASSWORD: fjalkshfklahs
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: fhasgkr867fa654
      ME_CONFIG_MONGODB_SERVER: nosqlmongo
    ports:
      - 8081:8081
    depends_on: 
      - nosqlmongo

  calendar_notifications:
    build: backend/calendarNotificationEvents/.
    image: calendar-notification-events:v1
    restart: always
    mem_limit: 512m
    cpus: 0.5
    depends_on: 
      - nosqlmongo
      - rabbitmq

  calendar_event_manager:
    build: backend/calendarEventManager/.
    image: calendar-event-manager:v1
    mem_limit: 512m
    cpus: 0.5
    restart: always
    ports:
      - 9090:9090
    depends_on: 
      - dbpostgres
      - rabbitmq

  build_angular_app:
    build: frontend/calendar-manager-ui/.
    image: builder-angular:v1
    volumes:
      - ./volumes/angular:/app/dist
    ports:
      - 4200:80
