# Use postgres/example user/password credentials
version: '3.1'

services:

  dbpostgres:
    image: postgres
    restart: always
    mem_limit: 512m
    cpus: 0.25
    environment:
      POSTGRES_PASSWORD: 1232451fafr8
      POSTGRES_USER: MsManager
      POSTGRES_DB: CalendarManager
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    network_mode: "host"  
   
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    mem_limit: 512m
    cpus: 0.25
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: gwohnfgj45*5
      RABBITMQ_DEFAULT_VHOST: dev
    ports:
      - 5672:5672
      - 8082:15672
    network_mode: "host"  
  nosqlmongo:
    image: mongo:5.0
    restart: always
    mem_limit: 512m
    cpus: 0.25
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: fhasgkr867fa654
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongodb:/data/db
    network_mode: "host"  
  

  # calendar_notifications:
  #   build: backend/calendarNotificationEvents/.
  #   image: calendar-notification-events:v1
  #   restart: always
  #   mem_limit: 512m
  #   cpus: 0.5
  #   depends_on: 
  #     - nosqlmongo
  #     - rabbitmq

  # calendar_event_manager:
  #   build: backend/CalendarEventManager/.
  #   image: calendar-event-manager:v1
  #   mem_limit: 512m
  #   cpus: 0.5
  #   restart: always
  #   ports:
  #     - 9090:9090
  #   depends_on: 
  #     - dbpostgres
  #     - rabbitmq

