# Use postgres/example user/password credentials
version: '3.1'

services:

  dbsql:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1232451fafr8
      POSTGRES_USER: MsManager
      POSTGRES_DB: CalendarManager
    ports:
      - 5432:5432