// Code generated by mockery v2.26.1. DO NOT EDIT.

package mocks

import (
	entities "github.com/LuisDiazM/calendar-manager/calendar-event-manager/domain/users/entities"
	mock "github.com/stretchr/testify/mock"
)

// UpdateUserRepository is an autogenerated mock type for the UpdateUserRepository type
type UpdateUserRepository struct {
	mock.Mock
}

// UpdateUser provides a mock function with given fields: user
func (_m *UpdateUserRepository) UpdateUser(user entities.Users) error {
	ret := _m.Called(user)

	var r0 error
	if rf, ok := ret.Get(0).(func(entities.Users) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUpdateUserRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewUpdateUserRepository creates a new instance of UpdateUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUpdateUserRepository(t mockConstructorTestingTNewUpdateUserRepository) *UpdateUserRepository {
	mock := &UpdateUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
